defaults:
  - override hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: standard
    cpus_per_task: 1
    mem_gb: 8
    timeout_min: 2880
    additional_parameters:
      nodelist: node021

runs: 10
threads: 1
outlier_thresh: 0.5 # percentage above the avg a run has to be to qualify as an outliar

layers: [8] # layers
cpoints: 3 # number of control points in the spline
range: 1 # range for the spline

batch_size: 10

relu_epochs: 0
spline_epochs: 0
both_epochs: 0
comp_relu: 0 # if switching to spline, save a version that you train on ReLU from the same initial model

lr_wb: 0.001 # initial learning rate for weights and biases
lr_bs: 0.0001 # learning rate for bspline
lrs: "none" # learning rate scheduler
lrs_gamma: .9
lrs_stepsize: 5

add_to_out: ""