defaults:
  - override hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: long
    cpus_per_task: 1
    mem_gb: 8
    timeout_min: 10080 # max: 7 days
    additional_parameters:
      nodelist: node022

runs: 100
threads: 1
outlier_thresh: 0.5 # percentage above the avg a run has to be to qualify as an outliar

layers: [8] # layers
cpoints: 3 # number of control points in the spline
range: 1 # range for the spline

batch_size: 10

relu_epochs: 0
bspline_epochs: 0
both_epochs: 0
lspline_epochs: 0
comp_relu: 0 # if switching to spline, save a version that you train on ReLU from the same initial model

lr_wb: 0.001 # (initial) learning rate for weights and biases
lr_bs: 0.0001 # (initial) learning rate for bspline
lr_ls: 0.0001 # (initial) learning rate for linear spline
lrs: "none" # learning rate scheduler
lrs_gamma: .9
lrs_stepsize: 5

output_dir: "."
bspline_order: ["bspline", "both"]

add_to_out: ""